apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: wordpress
spec:
  selector:
    app: nginx  # Ensure this selector matches your Nginx pod label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80  # Port inside the pod that Nginx is listening on
  type: LoadBalancer
